apiVersion: v1
kind: Service
metadata:
  name: app-serv
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
    nodePort: 30000